# Generated by Django 5.1.14 on 2025-11-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad_estimada', models.PositiveIntegerField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centroAnimal', to='examen.centro')),
                ('vacuna', models.ManyToManyField(blank=True, related_name='vacunasAnimal', to='examen.vacuna')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refugioCentro', to='examen.refugio'),
        ),
        migrations.CreateModel(
            name='Revision_veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_salud', models.PositiveIntegerField()),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalRevisionVeterinaria', to='examen.animal')),
            ],
        ),
    ]
